services:
  xspaces-recorder:
    image: ghcr.io/0xf3dz/twspace-dl@sha256:54f661ade6a16a8ba9f54703e4c43f8c18b1e4a0ee59870f737cd81a54cb9fe2
    container_name: xspaces-recorder
    restart: unless-stopped
    user: "${PUID}:${PGID}"
    env_file:
      - .env
    working_dir: /output
    volumes:
      - .:/output
    entrypoint:
      - dumb-init
      - --
      - sh
    command:
      - ./monitor.sh
    security_opt:
      - no-new-privileges:true
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
